global:
  scrape_interval: 10s  # Scrape every 10 seconds to match your script

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Check for HTTP 200-299 status codes
    static_configs:
      - targets:
        - https://fakestoreapi.com/products
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Address of blackbox exporter

  - job_name: 'scraper_app'
    static_configs:
      - targets: ['prometheus-scraper:8000']